// Generates app/utils/mdi-icons.ts: a tree-shakeable map of the project's used
// `mdi-*` icon names → @mdi/js SVG path constants. Source of truth is a grep of
// app/ for `mdi-*` literals. Run: `node scripts/gen-mdi-map.mjs`.
import { execSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import * as mdi from '@mdi/js'

const root = new URL('..', import.meta.url).pathname

// Exclude the icon-infrastructure files: they mention `mdi-*` as import paths /
// map keys (e.g. 'vuetify/iconsets/mdi-svg', '~/utils/mdi-icons'), not as icon
// usages. Everything else in app/ that says mdi-* is a real icon to ship.
const names = execSync(
  `grep -rohE "mdi-[a-z0-9-]+" "${root}/app" --exclude=vuetify-icons.ts --exclude=mdi-icons.ts`,
  { encoding: 'utf8' },
).split('\n').map(s => s.trim()).filter(Boolean)
const unique = [...new Set(names)].sort()

const toConst = kebab =>
  'mdi' + kebab.slice(4).split('-').map(s => s.charAt(0).toUpperCase() + s.slice(1)).join('')

const missing = []
const rows = []
for (const name of unique) {
  const c = toConst(name)
  if (typeof mdi[c] !== 'string') { missing.push(`${name} -> ${c}`); continue }
  rows.push({ name, c })
}

if (missing.length) {
  console.error('MISSING in @mdi/js:\n' + missing.join('\n'))
  process.exit(1)
}

const out = `// AUTO-GENERATED by scripts/gen-mdi-map.mjs — do not edit by hand.
// Maps the project's used \`mdi-*\` icon names to @mdi/js SVG path constants.
// Explicit named imports keep this tree-shakeable: only these ${rows.length} glyphs ship,
// not the full ~7000-glyph @mdi/font webfont. Re-run the generator after adding
// a new icon (it greps app/ for \`mdi-*\` literals).
import {
${rows.map(r => `  ${r.c},`).join('\n')}
} from '@mdi/js'

export const MDI_PATHS: Record<string, string> = {
${rows.map(r => `  '${r.name}': ${r.c},`).join('\n')}
}
`

writeFileSync(`${root}/app/utils/mdi-icons.ts`, out)
console.log(`wrote app/utils/mdi-icons.ts with ${rows.length} icons`)
